chat:
  enabled: true
  format: "<prefix><name><suffix> <reset><#809090>Â»</#809090> <white><message>"
  item:
    enabled: true
    permission: false

  messages:
    join: "<gray>[<green>+</green>]</gray> <green><name></green>"
    leave: "<gray>[<red>-</red>]</gray> <red><name></red>"

  filter:
    - nword:
        regex: \b(?!minigames?|shenanigans?)\w*n+ ?(?:i|1|!)+ ?g+ ?g?+ ?(?:e|a)?+ ?r?+\w*
        type: censor

  prefix:
    enabled: true
    blacklist:
      - badexample
    extra:
      - example:
          name: <light_purple>Example
          prefix: "<light_purple>[Example] "
          description:
            - "An example prefix added by default."
            - "You can remove this prefix from the Echogen config."

scoreboard:
  enabled: true
  title: "<red>scoreboard"
  lines:
    - "<aqua>test"
    - "<red>hi"
    - "<aqua>You are <player>"
  replacements:
    - line: 1
      mode: INSERT
      condition: "%player_is_flying% == yes"
      replacement: "<rainbow>You are flying"

    - line: 3
      condition: "%player_name% == FemboyEmir"
      regex: "<player>"
      replacement: "<pride:trans><player>"

    - line: 1
      condition:
        - "%player_name% == FemboyEmir"
        - "%player_gamemode% == CREATIVE"
      replacement: "test replaced"

    - mode: ADD
      condition: "%player_gamemode% == SURVIVAL"
      replacement: "<pride:gay>you are survivaling"

    - line: 1
      mode: DELETE
      condition: "%player_gamemode% != CREATIVE"